// Generated by Bisonc++ V5.02.00 on Sun, 15 Mar 2020 15:18:33 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {293, 1}, // 1: start ->  program
     {294, 3}, // 2: program ->  header declaration_block body
     {295, 3}, // 3: header (PROGRAM) ->  PROGRAM IDENTIFIER LINE_END
     {296, 0}, // 4: declaration_block ->  <empty>
     {296, 4}, // 5: declaration_block (DATA) ->  DATA COLON declaration declarations
     {299, 0}, // 6: declarations ->  <empty>
     {299, 3}, // 7: declarations (LINE_END) ->  declaration more_declaration LINE_END
     {300, 0}, // 8: more_declaration ->  <empty>
     {300, 3}, // 9: more_declaration (COMMA) ->  COMMA declaration more_declaration
     {298, 3}, // 10: declaration (IDENTIFIER) ->  IDENTIFIER TYPE type
     {301, 3}, // 11: type (I) ->  I #0001 B
     {302, 0}, // 12: #0001 ->  <empty>
     {297, 1}, // 13: body ->  expressions
     {303, 0}, // 14: expressions ->  <empty>
     {303, 2}, // 15: expressions ->  expression expressions
     {304, 1}, // 16: expression ->  read
     {304, 1}, // 17: expression ->  write
     {304, 1}, // 18: expression ->  assignment
     {304, 1}, // 19: expression ->  while_loop
     {304, 1}, // 20: expression ->  if_statement
     {305, 4}, // 21: read (READ) ->  READ TO IDENTIFIER LINE_END
     {306, 3}, // 22: write (WRITE) ->  WRITE expr LINE_END
     {307, 5}, // 23: assignment (MOVE) ->  MOVE expr TO IDENTIFIER LINE_END
     {308, 6}, // 24: while_loop (WHILE) ->  WHILE expr LINE_END expressions ENDWHILE LINE_END
     {309, 4}, // 25: if_statement (IF) ->  IF expr LINE_END if_second_half
     {311, 3}, // 26: if_second_half (ENDIF) ->  expressions ENDIF LINE_END
     {311, 5}, // 27: if_second_half (ELSE) ->  expressions ELSE expressions ENDIF LINE_END
     {310, 1}, // 28: expr (TRUE) ->  TRUE
     {310, 1}, // 29: expr (FALSE) ->  FALSE
     {310, 1}, // 30: expr (IDENTIFIER) ->  IDENTIFIER
     {310, 1}, // 31: expr (NATURAL_LITERAL) ->  NATURAL_LITERAL
     {310, 3}, // 32: expr (EQUAL) ->  expr EQUAL expr
     {310, 3}, // 33: expr (LEFT_PARENTHESIS) ->  LEFT_PARENTHESIS expr RIGHT_PARENTHESIS
     {310, 2}, // 34: expr (NOT) ->  NOT expr
     {310, 3}, // 35: expr (AND) ->  expr AND expr
     {310, 3}, // 36: expr (OR) ->  expr OR expr
     {310, 3}, // 37: expr (LESS_THAN) ->  expr LESS_THAN expr
     {310, 3}, // 38: expr (GREATER_THAN) ->  expr GREATER_THAN expr
     {310, 5}, // 39: expr (ADD) ->  ADD expr TO IDENTIFIER LINE_END
     {310, 5}, // 40: expr (SUBTRACT) ->  SUBTRACT expr FROM IDENTIFIER LINE_END
     {310, 4}, // 41: expr (MULTIPLY) ->  MULTIPLY IDENTIFIER BY expr
     {310, 4}, // 42: expr (DIVIDE) ->  DIVIDE IDENTIFIER BY expr
     {310, 6}, // 43: expr (MOD) ->  MOD IDENTIFIER BY expr TO IDENTIFIER
     {312, 1}, // 44: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 5} },           
    { {       293}, { 1} }, // start  
    { {       294}, { 2} }, // program
    { {       295}, { 3} }, // header 
    { {       257}, { 4} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  3} },                     
    { {     296}, {  5} }, // declaration_block
    { {     258}, {  6} }, // DATA             
    { {       0}, { -4} },                     
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       275}, { 7} }, // IDENTIFIER
    { {         0}, { 0} },              
};

SR__ s_5[] =
{
    { { REQ_DEF}, {  14} },                
    { {     297}, {   8} }, // body        
    { {     303}, {   9} }, // expressions 
    { {     304}, {  10} }, // expression  
    { {     305}, {  11} }, // read        
    { {     306}, {  12} }, // write       
    { {     307}, {  13} }, // assignment  
    { {     308}, {  14} }, // while_loop  
    { {     309}, {  15} }, // if_statement
    { {     268}, {  16} }, // READ        
    { {     269}, {  17} }, // WRITE       
    { {     264}, {  18} }, // MOVE        
    { {     273}, {  19} }, // WHILE       
    { {     270}, {  20} }, // IF          
    { {       0}, { -14} },                
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       280}, { 21} }, // COLON
    { {         0}, {  0} },         
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 22} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_10[] =
{
    { { REQ_DEF}, {  13} },                
    { {     303}, {  23} }, // expressions 
    { {     304}, {  10} }, // expression  
    { {     305}, {  11} }, // read        
    { {     306}, {  12} }, // write       
    { {     307}, {  13} }, // assignment  
    { {     308}, {  14} }, // while_loop  
    { {     309}, {  15} }, // if_statement
    { {     268}, {  16} }, // READ        
    { {     269}, {  17} }, // WRITE       
    { {     264}, {  18} }, // MOVE        
    { {     273}, {  19} }, // WHILE       
    { {     270}, {  20} }, // IF          
    { {       0}, { -14} },                
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       265}, { 24} }, // TO
    { {         0}, {  0} },      
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 25} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 37} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 38} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 39} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },               
    { {       298}, { 40} }, // declaration
    { {       275}, { 41} }, // IDENTIFIER 
    { {         0}, {  0} },               
};

SR__ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 42} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       279}, { 43} }, // LINE_END    
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 49} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 50} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 51} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 52} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 53} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 54} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 55} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       265}, { 56} }, // TO          
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       279}, { 57} }, // LINE_END    
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       279}, { 58} }, // LINE_END    
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_40[] =
{
    { { REQ_DEF}, {  4} },                
    { {     299}, { 59} }, // declarations
    { {     298}, { 60} }, // declaration 
    { {     275}, { 41} }, // IDENTIFIER  
    { {       0}, { -6} },                
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 61} }, // TYPE
    { {         0}, {  0} },        
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 62} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 63} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 64} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 65} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 66} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 67} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  7} },                     
    { {       277}, { 68} }, // RIGHT_PARENTHESIS
    { {       285}, { 44} }, // EQUAL            
    { {       282}, { 45} }, // AND              
    { {       283}, { 46} }, // OR               
    { {       286}, { 47} }, // LESS_THAN        
    { {       287}, { 48} }, // GREATER_THAN     
    { {         0}, {  0} },                     
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   4} },                
    { {     285}, {  44} }, // EQUAL       
    { {     286}, {  47} }, // LESS_THAN   
    { {     287}, {  48} }, // GREATER_THAN
    { {       0}, { -34} },                
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       265}, { 69} }, // TO          
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       266}, { 70} }, // FROM        
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       267}, { 71} }, // BY
    { {         0}, {  0} },      
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       267}, { 72} }, // BY
    { {         0}, {  0} },      
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       267}, { 73} }, // BY
    { {         0}, {  0} },      
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 74} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_DEF}, {  13} },                
    { {     303}, {  75} }, // expressions 
    { {     304}, {  10} }, // expression  
    { {     305}, {  11} }, // read        
    { {     306}, {  12} }, // write       
    { {     307}, {  13} }, // assignment  
    { {     308}, {  14} }, // while_loop  
    { {     309}, {  15} }, // if_statement
    { {     268}, {  16} }, // READ        
    { {     269}, {  17} }, // WRITE       
    { {     264}, {  18} }, // MOVE        
    { {     273}, {  19} }, // WHILE       
    { {     270}, {  20} }, // IF          
    { {       0}, { -14} },                
};

SR__ s_58[] =
{
    { { REQ_DEF}, {  14} },                  
    { {     311}, {  76} }, // if_second_half
    { {     303}, {  77} }, // expressions   
    { {     304}, {  10} }, // expression    
    { {     305}, {  11} }, // read          
    { {     306}, {  12} }, // write         
    { {     307}, {  13} }, // assignment    
    { {     308}, {  14} }, // while_loop    
    { {     309}, {  15} }, // if_statement  
    { {     268}, {  16} }, // READ          
    { {     269}, {  17} }, // WRITE         
    { {     264}, {  18} }, // MOVE          
    { {     273}, {  19} }, // WHILE         
    { {     270}, {  20} }, // IF            
    { {       0}, { -14} },                  
};

SR__ s_59[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_60[] =
{
    { { REQ_DEF}, {  3} },                    
    { {     300}, { 78} }, // more_declaration
    { {     278}, { 79} }, // COMMA           
    { {       0}, { -8} },                    
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       301}, { 80} }, // type
    { {       260}, { 81} }, // I   
    { {         0}, {  0} },        
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   3} },                
    { {     286}, {  47} }, // LESS_THAN   
    { {     287}, {  48} }, // GREATER_THAN
    { {       0}, { -32} },                
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   4} },                
    { {     285}, {  44} }, // EQUAL       
    { {     286}, {  47} }, // LESS_THAN   
    { {     287}, {  48} }, // GREATER_THAN
    { {       0}, { -35} },                
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   4} },                
    { {     285}, {  44} }, // EQUAL       
    { {     286}, {  47} }, // LESS_THAN   
    { {     287}, {  48} }, // GREATER_THAN
    { {       0}, { -36} },                
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 82} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 83} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 84} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 85} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       310}, { 86} }, // expr            
    { {       262}, { 26} }, // TRUE            
    { {       263}, { 27} }, // FALSE           
    { {       275}, { 28} }, // IDENTIFIER      
    { {       281}, { 29} }, // NATURAL_LITERAL 
    { {       276}, { 30} }, // LEFT_PARENTHESIS
    { {       284}, { 31} }, // NOT             
    { {       288}, { 32} }, // ADD             
    { {       289}, { 33} }, // SUBTRACT        
    { {       290}, { 34} }, // MULTIPLY        
    { {       291}, { 35} }, // DIVIDE          
    { {       292}, { 36} }, // MOD             
    { {         0}, {  0} },                    
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 87} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       274}, { 88} }, // ENDWHILE
    { {         0}, {  0} },            
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       272}, { 89} }, // ENDIF
    { {       271}, { 90} }, // ELSE 
    { {         0}, {  0} },         
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 91} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  3} },               
    { {       298}, { 92} }, // declaration
    { {       275}, { 41} }, // IDENTIFIER 
    { {         0}, {  0} },               
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   2} },         
    { {     302}, {  93} }, // #0001
    { {       0}, { -12} },         
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 94} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 95} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       265}, { 96} }, // TO          
    { {       285}, { 44} }, // EQUAL       
    { {       282}, { 45} }, // AND         
    { {       283}, { 46} }, // OR          
    { {       286}, { 47} }, // LESS_THAN   
    { {       287}, { 48} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 97} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       279}, { 98} }, // LINE_END
    { {         0}, {  0} },            
};

SR__ s_90[] =
{
    { { REQ_DEF}, {  13} },                
    { {     303}, {  99} }, // expressions 
    { {     304}, {  10} }, // expression  
    { {     305}, {  11} }, // read        
    { {     306}, {  12} }, // write       
    { {     307}, {  13} }, // assignment  
    { {     308}, {  14} }, // while_loop  
    { {     309}, {  15} }, // if_statement
    { {     268}, {  16} }, // READ        
    { {     269}, {  17} }, // WRITE       
    { {     264}, {  18} }, // MOVE        
    { {     273}, {  19} }, // WHILE       
    { {     270}, {  20} }, // IF          
    { {       0}, { -14} },                
};

SR__ s_91[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   3} },                    
    { {     300}, { 100} }, // more_declaration
    { {     278}, {  79} }, // COMMA           
    { {       0}, {  -8} },                    
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },     
    { {       261}, { 101} }, // B
    { {         0}, {   0} },     
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       275}, { 102} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       272}, { 103} }, // ENDIF
    { {         0}, {   0} },         
};

SR__ s_100[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   2} },            
    { {       279}, { 104} }, // LINE_END
    { {         0}, {   0} },            
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 31 "lang.y"
        {
         std::cout << "start -> program" << std::endl;
         }
        break;

        case 2:
#line 37 "lang.y"
        {
         std::cout << "program -> header declaration_block body" << std::endl;
         }
        break;

        case 3:
#line 43 "lang.y"
        {
         std::cout << "header -> PROGRAM IDENTIFIER LINE_END" << std::endl;
         }
        break;

        case 4:
#line 49 "lang.y"
        {
         std::cout << "declaration_block -> \"\"" << std::endl;
         }
        break;

        case 5:
#line 54 "lang.y"
        {
         std::cout << "declaration_block -> DATA COLON declaration declarationsa" << std::endl;
         }
        break;

        case 6:
#line 60 "lang.y"
        {
         std::cout << "declarations -> \"\"" << std::endl;
         }
        break;

        case 7:
#line 65 "lang.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 8:
#line 71 "lang.y"
        {
         std::cout << "more_declaration -> \"\"" << std::endl;
         }
        break;

        case 9:
#line 76 "lang.y"
        {
         std::cout << "more_declaration -> COMMA declaration more_declaration" << std::endl;
         }
        break;

        case 10:
#line 82 "lang.y"
        {
         std::cout << "declaration -> IDENTIFIER TYPE type" << std::endl;
         }
        break;

        case 11:
#line 93 "lang.y"
        {
         std::cout << "type -> B" << std::endl;
         }
        break;

        case 12:
#line 89 "lang.y"
        {
         std::cout << "type -> I" << std::endl;
         }
        break;

        case 13:
#line 99 "lang.y"
        {
         std::cout << "body -> expressions" << std::endl;
         }
        break;

        case 14:
#line 105 "lang.y"
        {
         std::cout << "expressions -> \"\"" << std::endl;
         }
        break;

        case 15:
#line 110 "lang.y"
        {
         std::cout << "expressions -> expression expressions" << std::endl;
         }
        break;

        case 16:
#line 117 "lang.y"
        {
         std::cout << "expressions -> read" << std::endl;
         }
        break;

        case 17:
#line 122 "lang.y"
        {
         std::cout << "expressions -> write" << std::endl;
         }
        break;

        case 18:
#line 127 "lang.y"
        {
         std::cout << "expressions -> assignment" << std::endl;
         }
        break;

        case 19:
#line 132 "lang.y"
        {
         std::cout << "expressions -> while_loop" << std::endl;
         }
        break;

        case 20:
#line 137 "lang.y"
        {
         std::cout << "expressions -> if_statement" << std::endl;
         }
        break;

        case 21:
#line 143 "lang.y"
        {
         std::cout << "read -> READ TO IDENTIFIER LINE_END" << std::endl;
         }
        break;

        case 22:
#line 149 "lang.y"
        {
         std::cout << "write -> WRITE expr" << std::endl;
         }
        break;

        case 23:
#line 155 "lang.y"
        {
         std::cout << "write -> MOVE expr TO IDENTIFIER LINE_END" << std::endl;
         }
        break;

        case 24:
#line 161 "lang.y"
        {
         std::cout << "while_loop -> WHILE expr LINE_END expressions ENDWHILE LINE_END" << std::endl;
         }
        break;

        case 25:
#line 167 "lang.y"
        {
         std::cout << "if_statement -> IF expr LINE_END if_second_half" << std::endl;
         }
        break;

        case 26:
#line 174 "lang.y"
        {
         std::cout << "if_second_half -> expressions ENDIF LINE_END" << std::endl;
         }
        break;

        case 27:
#line 179 "lang.y"
        {
         std::cout << "if_second_half -> expressions ELSE expressions ENDIF LINE_END" << std::endl;
         }
        break;

        case 28:
#line 186 "lang.y"
        {
         std::cout << "expr -> TRUE" << std::endl;
         }
        break;

        case 29:
#line 191 "lang.y"
        {
         std::cout << "expr -> FALSE" << std::endl;
         }
        break;

        case 30:
#line 196 "lang.y"
        {
         std::cout << "expr -> IDENTIFIER" << std::endl;
         }
        break;

        case 31:
#line 201 "lang.y"
        {
         std::cout << "expr -> NATURAL_LITERAL" << std::endl;
         }
        break;

        case 32:
#line 206 "lang.y"
        {
         std::cout << "expr -> expr EQUAL expr" << std::endl;
         }
        break;

        case 33:
#line 211 "lang.y"
        {
         std::cout << "expr -> LEFT_PARENTHESIS expr RIGHT_PARENTHESIS" << std::endl;
         }
        break;

        case 34:
#line 216 "lang.y"
        {
         std::cout << "expr -> NOT expr" << std::endl;
         }
        break;

        case 35:
#line 221 "lang.y"
        {
         std::cout << "expr -> expr AND expr" << std::endl;
         }
        break;

        case 36:
#line 226 "lang.y"
        {
         std::cout << "expr -> expr OR expr" << std::endl;
         }
        break;

        case 37:
#line 231 "lang.y"
        {
         std::cout << "expr -> expr LESS_THAN expr" << std::endl;
         }
        break;

        case 38:
#line 236 "lang.y"
        {
         std::cout << "expr -> expr GREATER_THAN expr" << std::endl;
         }
        break;

        case 39:
#line 241 "lang.y"
        {
         std::cout << "expr -> ADD expr TO IDENTIFIER LINE_END" << std::endl;
         }
        break;

        case 40:
#line 246 "lang.y"
        {
         std::cout << "expr -> SUBTRACT expr FROM IDENTIFIER LINE_END" << std::endl;
         }
        break;

        case 41:
#line 251 "lang.y"
        {
         std::cout << "expr -> MULTIPLY IDENTIFIER BY expr" << std::endl;
         }
        break;

        case 42:
#line 256 "lang.y"
        {
         std::cout << "expr -> DIVIDE IDENTIFIER BY expr" << std::endl;
         }
        break;

        case 43:
#line 261 "lang.y"
        {
         std::cout << "expr -> MOD IDENTIFIER BY exor TO IDENTIFIER" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



